# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class UiConnectToServerDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 250)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 391, 169))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.server_ip_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_ip_label.setFont(font)
        self.server_ip_label.setObjectName("server_ip_label")
        self.gridLayout.addWidget(self.server_ip_label, 0, 0, 1, 1)
        self.server_ip_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_ip_edit.sizePolicy().hasHeightForWidth())
        self.server_ip_edit.setSizePolicy(sizePolicy)
        self.server_ip_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_ip_edit.setFont(font)
        self.server_ip_edit.setInputMask("")
        self.server_ip_edit.setText("")
        self.server_ip_edit.setMaxLength(15)
        self.server_ip_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.server_ip_edit.setObjectName("server_ip_edit")
        self.gridLayout.addWidget(self.server_ip_edit, 1, 0, 1, 1)
        self.server_port_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_port_label.setFont(font)
        self.server_port_label.setObjectName("server_port_label")
        self.gridLayout.addWidget(self.server_port_label, 0, 1, 1, 1)
        self.server_port_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_port_edit.sizePolicy().hasHeightForWidth())
        self.server_port_edit.setSizePolicy(sizePolicy)
        self.server_port_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_port_edit.setFont(font)
        self.server_port_edit.setInputMask("")
        self.server_port_edit.setMaxLength(5)
        self.server_port_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.server_port_edit.setObjectName("server_port_edit")
        self.gridLayout.addWidget(self.server_port_edit, 1, 1, 1, 1)
        self.player_name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player_name_edit.sizePolicy().hasHeightForWidth())
        self.player_name_edit.setSizePolicy(sizePolicy)
        self.player_name_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.player_name_edit.setFont(font)
        self.player_name_edit.setMaxLength(20)
        self.player_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.player_name_edit.setObjectName("player_name_edit")
        self.gridLayout.addWidget(self.player_name_edit, 3, 0, 1, 2)
        self.player_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.player_name_label.setFont(font)
        self.player_name_label.setObjectName("player_name_label")
        self.gridLayout.addWidget(self.player_name_label, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.connect_button = QtWidgets.QPushButton(Dialog)
        self.connect_button.setGeometry(QtCore.QRect(10, 190, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Подключиться к серверу"))
        self.server_ip_label.setText(_translate("Dialog", "IP-Адрес сервера"))
        self.server_port_label.setText(_translate("Dialog", "Порт"))
        self.server_port_edit.setText(_translate("Dialog", "1337"))
        self.player_name_edit.setText(_translate("Dialog", "Player"))
        self.player_name_label.setText(_translate("Dialog", "Имя игрока"))
        self.connect_button.setText(_translate("Dialog", "Подключиться"))
