# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class UiServerStartDialog:
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 460)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 391, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.server_port_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_port_label.setFont(font)
        self.server_port_label.setObjectName("server_port_label")
        self.verticalLayout_2.addWidget(self.server_port_label)
        self.server_port_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_port_edit.sizePolicy().hasHeightForWidth())
        self.server_port_edit.setSizePolicy(sizePolicy)
        self.server_port_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.server_port_edit.setFont(font)
        self.server_port_edit.setInputMask("")
        self.server_port_edit.setMaxLength(5)
        self.server_port_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.server_port_edit.setObjectName("server_port_edit")
        self.verticalLayout_2.addWidget(self.server_port_edit)
        self.player_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.player_name_label.setFont(font)
        self.player_name_label.setObjectName("player_name_label")
        self.verticalLayout_2.addWidget(self.player_name_label)
        self.player_name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player_name_edit.sizePolicy().hasHeightForWidth())
        self.player_name_edit.setSizePolicy(sizePolicy)
        self.player_name_edit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.player_name_edit.setFont(font)
        self.player_name_edit.setMaxLength(20)
        self.player_name_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.player_name_edit.setObjectName("player_name_edit")
        self.verticalLayout_2.addWidget(self.player_name_edit)
        self.time_to_move_check = QtWidgets.QCheckBox(Dialog)
        self.time_to_move_check.setGeometry(QtCore.QRect(10, 200, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.time_to_move_check.setFont(font)
        self.time_to_move_check.setObjectName("time_to_move_check")
        self.time_to_move_spin = QtWidgets.QSpinBox(Dialog)
        self.time_to_move_spin.setEnabled(False)
        self.time_to_move_spin.setGeometry(QtCore.QRect(270, 200, 70, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.time_to_move_spin.setFont(font)
        self.time_to_move_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.time_to_move_spin.setMinimum(5)
        self.time_to_move_spin.setMaximum(300)
        self.time_to_move_spin.setProperty("value", 30)
        self.time_to_move_spin.setObjectName("time_to_move_spin")
        self.start_button = QtWidgets.QPushButton(Dialog)
        self.start_button.setGeometry(QtCore.QRect(10, 400, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 250, 391, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.first_move_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.first_move_label.setFont(font)
        self.first_move_label.setObjectName("first_move_label")
        self.verticalLayout_3.addWidget(self.first_move_label)
        self.random_button = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.random_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.random_button.setFont(font)
        self.random_button.setChecked(True)
        self.random_button.setObjectName("random_button")
        self.verticalLayout_3.addWidget(self.random_button)
        self.x_button = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.x_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.x_button.setFont(font)
        self.x_button.setObjectName("x_button")
        self.verticalLayout_3.addWidget(self.x_button)
        self.o_button = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.o_button.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.o_button.setFont(font)
        self.o_button.setObjectName("o_button")
        self.verticalLayout_3.addWidget(self.o_button)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Запуск сервера"))
        self.server_port_label.setText(_translate("Dialog", "Порт сервера (0-65535)"))
        self.server_port_edit.setText(_translate("Dialog", "1337"))
        self.player_name_label.setText(_translate("Dialog", "Имя игрока"))
        self.player_name_edit.setText(_translate("Dialog", "Host"))
        self.time_to_move_check.setText(_translate("Dialog", "Ограничить время на ход"))
        self.start_button.setText(_translate("Dialog", "Запустить сервер"))
        self.first_move_label.setText(_translate("Dialog", "Первый ход"))
        self.random_button.setText(_translate("Dialog", "Случайный выбор"))
        self.x_button.setText(_translate("Dialog", "❌"))
        self.o_button.setText(_translate("Dialog", "⭕"))
